### PR TITLE
fix: update persian translation

### PR DESCRIPTION
**Pull request by eshagh79**
## Description

update persian translation

### Checklist:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Have you linted your code locally prior to submission?
* [x] Have you successfully ran app with your changes locally?

### CODE REVIEW

**Comment by agalwood** [comment]
Hi @eshagh79, first of all thank you for your PR.

I have a doubt, why there are so many differences between your translation and the original Persian contributor’s submission?

**Comment by eshagh79** [comment]
Hi
The previous translator had tried to translate the sentences into Persian with translation machines such as Google Translator.
In most of the sentences, the grammar was not observed and he did not try to use the equivalent words in Persian.
For example, in Persian, "task" == is "وظیفه", but he translated it as "تسک", which gave the exact sound of task, but we do not have such a word in Persian, but it is used among people.
T = 'ت'
S = 'س'
K = 'ک'
And many other words that are the same, that is, although they are used among the people, but they are not Persian words
For example, the word "آپدیت" is used among people, but the correct word is "به‌روز رسانی" = (update).
Although I tried to improve this translation, it is still incomplete and has problems.

**Comment by agalwood** [comment]
WIP or completed? Can I merge it now?

**Comment by eshagh79** [comment]
It is much better now.
You can merge.

**Pull request merged**
