### PR TITLE
Added Hindi Localization

### PR DESCRIPTION
**Pull request by rajendrakumaryadav**
## Description
Added Hindi Localization..

## Related Issues
* I can run it local but on push git have some issues.
* At local development machine, I am able to build. But I am not sure that How I can add node_modules/element-ui/lib/locale/lang/hi.js (Please guide me to add the file into source.
build-completed

### Checklist:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Have you linted your code locally prior to submission?
* [x] Have you successfully ran app with your changes locally?

### CODE REVIEW

**Comment by agalwood** [comment]
I think you may need to submit a `Hindi` i18n PR to Element UI.

Element UI
https://element.eleme.io/#/en-US/component/i18n

> If your target language is not included, you are more than welcome to contribute: just add another language config here and create a pull request.

https://github.com/ElemeFE/element/tree/dev/src/locale/lang

**Comment by rajendrakumaryadav** [comment]
```js
'use strict';

exports.__esModule = true;
exports.default = {
  el: {
    colorpicker: {
      confirm: 'ठीक',
      clear: 'Clear'
    },
    datepicker: {
      now: 'अभी',
      today: 'आज',
      cancel: 'रद्द करना',
      clear: 'हटाना',
      confirm: 'ठीक',
      selectDate: 'तारीख़ चुनें',
      selectTime: 'समय चुनें',
      startDate: 'आरंभ करने की तारीख़',
      startTime: 'शुरू करने की समय',
      endDate: 'अंतिम तिथि',
      endTime: 'अंतिम समय',
      prevYear: 'पिछला वर्ष',
      nextYear: 'अगले वर्ष',
      prevMonth: 'पिछ्ला महिना',
      nextMonth: 'अगले महीना',
      year: '',
      month1: 'January',
      month2: 'February',
      month3: 'March',
      month4: 'April',
      month5: 'May',
      month6: 'June',
      month7: 'July',
      month8: 'August',
      month9: 'September',
      month10: 'October',
      month11: 'November',
      month12: 'December',
      week: 'week',
      weeks: {
        sun: 'Sun',
        mon: 'Mon',
        tue: 'Tue',
        wed: 'Wed',
        thu: 'Thu',
        fri: 'Fri',
        sat: 'Sat'
      },
      months: {
        jan: 'Jan',
        feb: 'Feb',
        mar: 'Mar',
        apr: 'Apr',
        may: 'May',
        jun: 'Jun',
        jul: 'Jul',
        aug: 'Aug',
        sep: 'Sep',
        oct: 'Oct',
        nov: 'Nov',
        dec: 'Dec'
      }
    },
    select: {
      loading: 'Loading',
      noMatch: 'No matching data',
      noData: 'No data',
      placeholder: 'Select'
    },
    cascader: {
      noMatch: 'No matching data',
      loading: 'Loading',
      placeholder: 'Select',
      noData: 'No data'
    },
    pagination: {
      goto: 'Go to',
      pagesize: '/page',
      total: 'Total {total}',
      pageClassifier: ''
    },
    messagebox: {
      title: 'संदेश',
      confirm: 'ठीक',
      cancel: 'रद्द',
      error: 'अवैध इनपुट'
    },
    upload: {
      deleteTip: 'press delete to remove',
      delete: 'हटाएं',
      preview: 'पूर्वावलोकन',
      continue: 'जारी रखें'
    },
    table: {
      emptyText: 'No Data',
      confirmFilter: 'Confirm',
      resetFilter: 'Reset',
      clearFilter: 'All',
      sumText: 'Sum'
    },
    tree: {
      emptyText: 'No Data'
    },
    transfer: {
      noMatch: 'No matching data',
      noData: 'No data',
      titles: ['List 1', 'List 2'], // to be translated
      filterPlaceholder: 'Enter keyword', // to be translated
      noCheckedFormat: '{total} items', // to be translated
      hasCheckedFormat: '{checked}/{total} checked' // to be translated
    },
    image: {
      error: 'असफल'
    },
    pageHeader: {
      title: 'Back' // to be translated
    },
    popconfirm: {
      confirmButtonText: 'हाँ',
      cancelButtonText: 'नहीं'
    }
  }
};
```
node_modules/element-ui/lib/locale/lang/hi.js
* Please guide me to add this in default npm install package.

Thanks you...

**Comment by rajendrakumaryadav** [comment]
> I think you may need to submit a `Hindi` i18n PR to Element UI.
> 
> Element UI
> https://element.eleme.io/#/en-US/component/i18n
> 
> > If your target language is not included, you are more than welcome to contribute: just add another language config here and create a pull request.
> 
> https://github.com/ElemeFE/element/tree/dev/src/locale/lang

Sure...

**Comment by agalwood** [comment]
Like this PR : )
https://github.com/ElemeFE/element/pull/19320

**Comment by rajendrakumaryadav** [comment]
> Like this PR : )
> [ElemeFE/element#19320](https://github.com/ElemeFE/element/pull/19320)

Pull request added for ElemeFE [Locale: Added Hindi #19727](https://github.com/ElemeFE/element/pull/19727)

**Comment by agalwood** [comment]
I found that the PR(https://github.com/ElemeFE/element/pull/19727) you submitted to Element UI included `package-lock.json`. The Element UI team used yarn. I think you should remove the `package-lock.json` from your PR.

**Comment by rajendrakumaryadav** [comment]
> I found that the PR([ElemeFE/element#19727](https://github.com/ElemeFE/element/pull/19727)) you submitted to Element UI included `package-lock.json`. The Element UI team used yarn. I think you should remove the `package-lock.json` from your PR.

package-lock.json removed.

**Comment by agalwood** [comment]
You misunderstood, it is not for you to remove Motrix's package-lock.json! It's Element UI! These are two repo.

> https://github.com/ElemeFE/element/pull/19727

**Comment by rajendrakumaryadav** [comment]
Ook, **No issuess..**

**Pull request closed without merging**
