### PR TITLE
feat: Add Arabic Localization (partially, need help).

### PR DESCRIPTION
**Pull request by hadialqattan**
## Description
Support the Arabic language partially!

## Related Issues
None.

### Checklist:

* [X] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Have you linted your code locally prior to submission?
* [x] Have you successfully ran app with your changes locally?

### CODE REVIEW

**Comment by hadialqattan** [comment]
Please don't merge, just review...

**I need some help from a native Arabic speaker to discuss some translation-related stuff!**

**Comment by jimman2003** [comment]
You can draft your PR as to convey your intent better

**Review by a17assn — APPROVED** [review]

**Comment by AhmedElTabarani** [comment]
@agalwood 
Why did you marged it now?
i was working on it 

Now should I make a new pull request or update and edit this on?

**Comment by agalwood** [comment]
I misunderstood this message, thinking you have finished the translation, so I merged it.

> a17assn approved these changes 13 hours ago

Please open a new PR, thank you. @AhmedElTabarani

**Comment by hadialqattan** [comment]
@AhmedElTabarani Hi, kindly, please don't remove my name!

\+ please let me know when you need any help, I'm a native Arabic speaker (from SA)!

Best, 

Hadi.

**Comment by AhmedElTabarani** [comment]
don't worry about your name, I will put your name only,  I'll just do the rest.

@agalwood  can't put more than one name right?

**Comment by AhmedElTabarani** [comment]
> please let me know when you need any help, I'm a native Arabic speaker (from SA)!, I'm a native Arabic speaker (from SA)!

Don't worry i got it ☺️، i am from Egypt anyway
Nice work to start this pull request.
I think after finish this, we should do a RTL UI !

**Comment by hadialqattan** [comment]
> don't worry about your name, I will put your name only, I'll just do the rest.
> 
> @agalwood can't put more than one name right?

I hope @agalwood allows us to put more than one name!

**Comment by hadialqattan** [comment]
> > please let me know when you need any help, I'm a native Arabic speaker (from SA)!, I'm a native Arabic speaker (from SA)!
> 
> Don't worry i got it ☺️، i am from Egypt anyway
> Nice work to start this pull request.
> I think after finish this, we should do a RTL UI !

Nice!
Yeah, I agree, the LTR isn't that good with Arabic!

Appreciations 🌹

**Comment by agalwood** [comment]
Sorry, it looks like I am @ the wrong person : (

Your translation contributions are welcome, and I will add your names to the list of translation contributors.
@hadialqattan @AhmedElTabarani

**Comment by AhmedElTabarani** [comment]
@agalwood  i complete it, but i have some question

1. spaces before functions

```js
function checkLngIsAvailable (locale)

export function getLanguage (locale = 'en-US')
``` 

I can't do `npm run dev` until put space before these function, why ? and should i push it with this space ?

2.
After i install npm files, There is some modifies occurred on the yarn file, should i push it?

3.
I should not upload the package-lock.json file, right ?

**Pull request merged**
