### PR TITLE
feat: Allow more customization for transfer speeds

### LINKED ISSUE #808: Can I custom the download limit speed?
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
[
Screenshot from 2020-11-22 15-52-35
](url)

### LINKED ISSUE #860: Please add more speed limit options
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Please add more download speed limit options like 2 MB/s, 3 MB/s etc.
Thank you.

**Describe alternatives you've considered**
resim

**Additional context**
*

### LINKED ISSUE #1231: Allow for more granular control over transmission rate limiting
**Is your feature request related to a problem? Please describe.**
I use the transmission rate limiting feature to limit my download speed, however I find that sometimes I want a rate that is between the preset values on the dropdown menu, but I don't have that option.

**Describe the solution you'd like**
I'd like to see the ability to use a custom value for download (and upload) speed limits. An example I've seen of this feature is the "limit bandwidth" options in the downloads settings of the Steam games client (picture included for reference).

**Describe alternatives you've considered**
My ideas are to either replace the dropdown menu with a text input form (same thing as the example with Steam), or adding "custom" as an option on the dropdown menu that will then give a text input form. Anything that allows for custom rate limit values and is shown in the basic settings is welcome.

**Additional context**
An example implementation of the feature I want, taken from a different piece of software. A text input form for rate limiting with custom values. This screenshot was taken from the Steam games client. In the screenshot, the download rate is limited to the custom value of 800 KB/s.
image
In comparison, I would not be able to set the same value on Motrix, only 512 KB/s which is lower or 1 MB/s which is higher.
motrix

### PR DESCRIPTION
**Pull request by SammCheese**
## Description
This PR adds an Input field and a unit selector to transfer speeds.
This allows the user to Tweak speeds more to their likings.
Images Attached

image

## Related Issues
Fixes #808
Fixes #1231
Fixes #860

### Checklist:

* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [x] Have you linted your code locally prior to submission?
* [x] Have you successfully ran app with your changes locally?

### CODE REVIEW

**Comment by agalwood** [comment]
I think it is possible to maintain the original maxOverallDownloadLimit and maxOverallUploadLimit data structures. There is no need to introduce uploadUinit and downloadUnit in userKeys. You can get units (G, M, K) through parseInt and then replace, and computed to output uploadUnit and downloadUnit.

**Comment by SammCheese** [comment]
This should address your concerns regarding userKeys and the change of data structures.

**Comment by agalwood** [comment]
Nice job!  Thanks for your contribution 👍

**Comment by shatyuka** [comment]
I got maxOverallDownloadLimit = number 0 here, means no limitation.
https://github.com/agalwood/Motrix/blob/7201f17aed174e883317f14e16fc0e4a4c5083af/src/renderer/components/Preference/Basic.vue#L415-L417

https://github.com/agalwood/Motrix/blob/b4df97b4714846078630c33f05060a0385a8f132/src/renderer/components/Preference/Basic.vue#L401-L406

So it's not upgradable from older version.

**Comment by SammCheese** [comment]
I have not considered that. I will try to fix that as soon as i can.

**Pull request merged**
